/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaurieMooPackage;

/**
 *
 * @author Matthew Walker
 */
public class LaurieMooJFrame extends javax.swing.JFrame {
    private GuessRandomValue rndValue = new GuessRandomValue();
    
    /**
     * Creates new form LaurieMooJFrame
     */
    public LaurieMooJFrame() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.CYAN);      //Set Background color to CYAN
        
        rndValue.setAnswer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerLabel = new javax.swing.JLabel();
        answerTxtFld = new javax.swing.JTextField();
        guessLavel = new javax.swing.JLabel();
        guessTxtFld = new javax.swing.JTextField();
        bigMooLabel = new javax.swing.JLabel();
        bigMooNumLabel = new javax.swing.JLabel();
        mooLabel = new javax.swing.JLabel();
        mooNumLabel = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        correctLabel = new javax.swing.JLabel();
        randomBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        answerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        answerLabel.setText("Answer:");

        answerTxtFld.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        answerTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerTxtFld.setText("0000");
        answerTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTxtFldActionPerformed(evt);
            }
        });

        guessLavel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        guessLavel.setText("Guess:");

        guessTxtFld.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        guessTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessTxtFld.setText("0000");
        guessTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTxtFldActionPerformed(evt);
            }
        });

        bigMooLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        bigMooLabel.setText("Number of MOO!");

        bigMooNumLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        bigMooNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bigMooNumLabel.setText("0");

        mooLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        mooLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mooLabel.setText("Number of moo.");

        mooNumLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        mooNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mooNumLabel.setText("0");

        guessLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        guessLabel.setText("Is correct guess:");

        correctLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        correctLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctLabel.setText("   ");

        randomBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        randomBtn.setText("random");
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guessLabel)
                    .addComponent(mooLabel)
                    .addComponent(bigMooLabel)
                    .addComponent(guessLavel)
                    .addComponent(answerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(answerTxtFld)
                    .addComponent(guessTxtFld)
                    .addComponent(bigMooNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mooNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correctLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(randomBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerLabel)
                    .addComponent(randomBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessLavel)
                    .addComponent(guessTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigMooLabel)
                    .addComponent(bigMooNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mooLabel)
                    .addComponent(mooNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessLabel)
                    .addComponent(correctLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTxtFldActionPerformed
        if( answerTxtFld.getText().length() < 5)
            rndValue.setAnswer(Integer.parseInt(answerTxtFld.getText()));
        else
            answerTxtFld.setText(rndValue.getAnswer());
    }//GEN-LAST:event_answerTxtFldActionPerformed

    private void guessTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTxtFldActionPerformed
       bigMooNumLabel.setText(Integer.toString(rndValue.getBigMooCount(Integer.parseInt(guessTxtFld.getText()))));
       mooNumLabel.setText(Integer.toString(rndValue.getLittleMooCount(Integer.parseInt(guessTxtFld.getText()))));
       
       if(rndValue.isCorrectGuess(Integer.parseInt(guessTxtFld.getText())))
           correctLabel.setText("yes");
       else 
           correctLabel.setText("no");
    }//GEN-LAST:event_guessTxtFldActionPerformed

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        rndValue.setAnswer();
        answerTxtFld.setText(rndValue.getAnswer());
    }//GEN-LAST:event_randomBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaurieMooJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField answerTxtFld;
    private javax.swing.JLabel bigMooLabel;
    private javax.swing.JLabel bigMooNumLabel;
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel guessLavel;
    private javax.swing.JTextField guessTxtFld;
    private javax.swing.JLabel mooLabel;
    private javax.swing.JLabel mooNumLabel;
    private javax.swing.JButton randomBtn;
    // End of variables declaration//GEN-END:variables
}
