/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaurieMoo;

import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author Matthew Walker
 * 23 January 2018
 */
public class LaurieMooJFrame extends javax.swing.JFrame {
    // instance variables of the main class
    private final GuessRandomValue randomValue = new GuessRandomValue();
    private final int MAX_GUESSES = 10; //maximum number of guesses allowed by player
    private int guessCounter = 1;
    /**
     * Creates new form LaurieMooJFrame
     */
    public LaurieMooJFrame() {
        initComponents();
        randomValue.setAnswer();
        newGameButton.setEnabled(false);    //sets new game value as grayed out
        answerList.setEnabled(false);       //sets answer list as grayed
        answerMooList.setEnabled(false);
        getContentPane().setBackground(java.awt.Color.CYAN);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        answerJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerList = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        answerMooList = new javax.swing.JTextArea();
        mooLabel4 = new javax.swing.JLabel();
        mooLabel1 = new javax.swing.JLabel();
        mooLabel2 = new javax.swing.JLabel();
        mooLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LaurieMOO!");

        guessLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        guessLabel.setText("Guess #1:");

        answerJTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Previous Guesses:");

        newGameButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        answerList.setColumns(9);
        answerList.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerList.setRows(1);
        answerList.setAutoscrolls(false);
        jScrollPane1.setViewportView(answerList);
        answerList.setLineWrap(true);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" Big Little");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        answerMooList.setColumns(2);
        answerMooList.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerMooList.setLineWrap(true);
        answerMooList.setRows(9);
        answerMooList.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(answerMooList);
        answerList.setAutoscrolls(false);

        mooLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        mooLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mooLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        mooLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mooLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        mooLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mooLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        mooLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(guessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mooLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mooLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mooLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mooLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mooLabel1, mooLabel2, mooLabel3, mooLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mooLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mooLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mooLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mooLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(149, 149, 149)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mooLabel1, mooLabel2, mooLabel3, mooLabel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void answerJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerJTextFieldActionPerformed
        
        // restricting to 4 digits
        if(answerJTextField.getText().length()>4 || answerJTextField.getText().length() <4) {  
          JOptionPane.showMessageDialog(null, "Please only enter a 4 digit number");
          answerJTextField.setText("");
        }
        
        else{
        // Updating the guess label eveytime
        guessLabel.setText("Guess #" + (guessCounter +1) + ":");
        
        // Game win message
        if(randomValue.isCorrectGuess(Integer.parseInt(answerJTextField.getText()))){
            guessLabel.setText("Guess #" + (guessCounter) + ":");   //shows the final guess #
            answerJTextField.setText(answerJTextField.getText());   //shows the final guess
            JOptionPane.showMessageDialog(null, "LaurieMOO!!" + "\n" + "Click new game or X out to quit playing.");
            newGameButton.setEnabled(true);
            answerJTextField.setEnabled(false);
        }
        // Game loss message
        if (guessCounter == MAX_GUESSES && !randomValue.isCorrectGuess(Integer.parseInt(answerJTextField.getText()))){
            guessLabel.setText("Guess #10:");
            JOptionPane.showMessageDialog(null, "Boo hoo...No LaurieMoo for you" + "\n" + "The correct answer is: " + randomValue.getAnswer() + "."); 
            newGameButton.setEnabled(true);
            answerJTextField.setEnabled(false);
        }
        guessCounter++; //Increments # of guesses
        int bigMooCount = randomValue.getBigMooCount(Integer.parseInt(answerJTextField.getText()));
        int littleMooCount = randomValue.getLittleMooCount(Integer.parseInt(answerJTextField.getText()));
        
        // Clearing mooLabels before the guess change
        mooLabel1.setText("");
        mooLabel2.setText("");
        mooLabel3.setText("");
        mooLabel4.setText("");
        
        // printing out moos
        if (littleMooCount == 1){mooLabel1.setText("moo.");}
        if (littleMooCount == 2){mooLabel1.setText("moo."); mooLabel2.setText("moo.");}
        if (littleMooCount == 3){mooLabel1.setText("moo."); mooLabel2.setText("moo."); mooLabel3.setText("moo.");}
        if (littleMooCount == 4){mooLabel1.setText("moo."); mooLabel2.setText("moo."); mooLabel3.setText("moo."); mooLabel4.setText("moo.");}
        
        //printing out MOO's
        if (bigMooCount == 1){mooLabel4.setText("MOO!");}
        if (bigMooCount == 2){mooLabel4.setText("MOO!"); mooLabel3.setText("MOO!");}
        if (bigMooCount == 3){mooLabel4.setText("MOO!"); mooLabel3.setText("MOO!"); mooLabel2.setText("MOO!");}
        if (bigMooCount == 4){mooLabel4.setText("MOO!"); mooLabel3.setText("MOO!"); mooLabel2.setText("MOO!"); mooLabel1.setText("MOO!");}
        
        // adding the guess to the answerList
      
        ArrayList<String> previousGuess = new ArrayList<>(); //creates a modular arrayList
        
        previousGuess.add(answerJTextField.getText()); //updates the arrayList with each input
      
        answerList.append(previousGuess.toString() + "\n"); //appends and outputs each input to the textArea
        
        answerJTextField.setText("");
        
        // adding the moos to the answer list
        
        ArrayList<Integer> mooGuess = new ArrayList<>();
        
        mooGuess.add(bigMooCount);
        mooGuess.add(littleMooCount);
        
        answerMooList.append(mooGuess + "\n");
        }
    }//GEN-LAST:event_answerJTextFieldActionPerformed
    
    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        //Resets all variables
        newGameButton.setEnabled(false);
        answerJTextField.setText("");
        randomValue.setAnswer();
        guessCounter = 1;
        guessLabel.setText("Guess #" + guessCounter + ":");
        answerList.setText("");
        mooLabel1.setText("");
        mooLabel2.setText("");
        mooLabel3.setText("");
        mooLabel4.setText("");
        answerList.setEnabled(false);
        answerJTextField.setEnabled(true);
        answerMooList.setText("");
        
    }//GEN-LAST:event_newGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaurieMooJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LaurieMooJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerJTextField;
    private javax.swing.JTextArea answerList;
    private javax.swing.JTextArea answerMooList;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mooLabel1;
    private javax.swing.JLabel mooLabel2;
    private javax.swing.JLabel mooLabel3;
    private javax.swing.JLabel mooLabel4;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
